In [1]:
import json
from pandas.io.json import json_normalize

In [2]:
#ACTIVITY

#Get Daily Activity Summary 

DaySum = [{
"activities": [],
"goals": [{
"activeMinutes": 30,
"caloriesOut": 1977,
"distance": 8.05,
"floors": 10,
"steps": 8000
}],
"summary": [{
"activeScore": -1,
"activityCalories": 1259,
"caloriesBMR": 1100,
"caloriesOut": 2079,
"distances": [
{
"activity": "total",
"distance": 10.34
},
{
"activity": "tracker",
"distance": 10.34
},
{
"activity": "loggedActivities",
"distance": 0
},
{
"activity": "veryActive",
"distance": 2.36
},
{
"activity": "moderatelyActive",
"distance": 0.39
},
{
"activity": "lightlyActive",
"distance": 7.56
},
{
"activity": "sedentaryActive",
"distance": 0
}
],
"elevation": 48.77,
"fairlyActiveMinutes": 11,
"floors": 16,
"heartRateZones": [
{
"caloriesOut": 1584.9834,
"max": 94,
"min": 30,
"minutes": 1311,
"name": "Out of Range"
},
{
"caloriesOut": 264.71172,
"max": 131,
"min": 94,
"minutes": 66,
"name": "Fat Burn"
},
{
"caloriesOut": 103.80552,
"max": 159,
"min": 131,
"minutes": 15,
"name": "Cardio"
},
{
"caloriesOut": 98.76048,
"max": 220,
"min": 159,
"minutes": 13,
"name": "Peak"
}
],
"lightlyActiveMinutes": 366,
"marginalCalories": 658,
"restingHeartRate": 51,
"sedentaryMinutes": 743,
"steps": 16248,
"veryActiveMinutes": 40
}]
}]

In [3]:
a = json_normalize(DaySum, 'goals')

In [4]:
a #for values to appear, need to make sure feature and values are within dic within a list

#(These are my baseline values)

activeMinutes  caloriesOut  distance  floors  steps
0             30         1977      8.05      10   8000

In [5]:
#On small scale:

##relevant features##
small_X = a.drop('caloriesOut', axis = 1)
small_X

activeMinutes  distance  floors  steps
0             30      8.05      10   8000

In [6]:
small_y = a[['caloriesOut']]
small_y

caloriesOut
0         1977

In [7]:
b = json_normalize(DaySum, 'summary')

In [8]:
b #These are acutal features I want to use in my Matrix X,y; need to figure out how to get multiple entries with dates attached

#Solution: Further down in notebook: will grab relevant feature values within a month's span and join these features on day
#in order to get multiple feature readings per day for multiple days 

activeScore  activityCalories  caloriesBMR  caloriesOut  \
0           -1              1259         1100         2079   

                                           distances  elevation  \
0  [{u'distance': 10.34, u'activity': u'total'}, ...      48.77   

   fairlyActiveMinutes  floors  \
0                   11      16   

                                      heartRateZones  lightlyActiveMinutes  \
0  [{u'max': 94, u'caloriesOut': 1584.9834, u'min...                   366   

   marginalCalories  restingHeartRate  sedentaryMinutes  steps  \
0               658                51               743  16248   

   veryActiveMinutes  
0                 40

In [9]:
b['distances']

0    [{u'distance': 10.34, u'activity': u'total'}, ...
Name: distances, dtype: object

In [10]:
#Candidate Features

##'elevation', 'fairlyActiveMinutes', 'steps', 'veryActiveMinutes'

#Candidate y values. These are going to be run one at a time for every feature set

##'activeScore', 'activityCalories', 'caloriesBMR', 'caloriesOut', 'marginalCalories'

##e.g. 'elevation', 'fairlyActiveMinutes', 'steps', 'veryActiveMinutes' -> 'activeScore'
    # 'elevation', 'fairlyActiveMinutes', 'steps', 'veryActiveMinutes' -> 'activityCalories'

In [11]:
# new = old[['A', 'C', 'D']].copy()

med_X = b[['elevation', 'fairlyActiveMinutes', 'floors', 'steps', 'veryActiveMinutes']].copy()
med_X

elevation  fairlyActiveMinutes  floors  steps  veryActiveMinutes
0      48.77                   11      16  16248                 40

In [12]:
med_y_sample1 = b[['activeScore']]
med_y_sample1

activeScore
0           -1

In [13]:
med_y_sample2 = b[['activityCalories']]
med_y_sample2

activityCalories
0              1259

In [14]:
#Get elevation Time Series

elev = [{
"activities-elevation": [
{
"dateTime": "2017-05-01",
"value": "67"
},
{
"dateTime": "2017-05-02",
"value": "30"
},
{
"dateTime": "2017-05-03",
"value": "27"
},
{
"dateTime": "2017-05-04",
"value": "39"
},
{
"dateTime": "2017-05-05",
"value": "18"
},
{
"dateTime": "2017-05-06",
"value": "51"
},
{
"dateTime": "2017-05-07",
"value": "48"
},
{
"dateTime": "2017-05-08",
"value": "27"
},
{
"dateTime": "2017-05-09",
"value": "33"
},
{
"dateTime": "2017-05-10",
"value": "27"
},
{
"dateTime": "2017-05-11",
"value": "15"
},
{
"dateTime": "2017-05-12",
"value": "21"
},
{
"dateTime": "2017-05-13",
"value": "21"
},
{
"dateTime": "2017-05-14",
"value": "15"
},
{
"dateTime": "2017-05-15",
"value": "3"
},
{
"dateTime": "2017-05-16",
"value": "6"
},
{
"dateTime": "2017-05-17",
"value": "3"
},
{
"dateTime": "2017-05-18",
"value": "33"
},
{
"dateTime": "2017-05-19",
"value": "24"
},
{
"dateTime": "2017-05-20",
"value": "64"
},
{
"dateTime": "2017-05-21",
"value": "24"
},
{
"dateTime": "2017-05-22",
"value": "54"
},
{
"dateTime": "2017-05-23",
"value": "24"
},
{
"dateTime": "2017-05-24",
"value": "36"
},
{
"dateTime": "2017-05-25",
"value": "24"
},
{
"dateTime": "2017-05-26",
"value": "18"
},
{
"dateTime": "2017-05-27",
"value": "36"
},
{
"dateTime": "2017-05-28",
"value": "42"
},
{
"dateTime": "2017-05-29",
"value": "76"
},
{
"dateTime": "2017-05-30",
"value": "27"
},
{
"dateTime": "2017-05-31",
"value": "21"
}
]
}]

In [15]:
c = json_normalize(elev, 'activities-elevation')
c

dateTime value
0   2017-05-01    67
1   2017-05-02    30
2   2017-05-03    27
3   2017-05-04    39
4   2017-05-05    18
5   2017-05-06    51
6   2017-05-07    48
7   2017-05-08    27
8   2017-05-09    33
9   2017-05-10    27
10  2017-05-11    15
11  2017-05-12    21
12  2017-05-13    21
13  2017-05-14    15
14  2017-05-15     3
15  2017-05-16     6
16  2017-05-17     3
17  2017-05-18    33
18  2017-05-19    24
19  2017-05-20    64
20  2017-05-21    24
21  2017-05-22    54
22  2017-05-23    24
23  2017-05-24    36
24  2017-05-25    24
25  2017-05-26    18
26  2017-05-27    36
27  2017-05-28    42
28  2017-05-29    76
29  2017-05-30    27
30  2017-05-31    21

In [16]:
# Get fairlyActiveMinutes Time Series

fairlyAct = [{
"activities-minutesFairlyActive": [
{
"dateTime": "2017-05-01",
"value": "13"
},
{
"dateTime": "2017-05-02",
"value": "5"
},
{
"dateTime": "2017-05-03",
"value": "8"
},
{
"dateTime": "2017-05-04",
"value": "19"
},
{
"dateTime": "2017-05-05",
"value": "21"
},
{
"dateTime": "2017-05-06",
"value": "2"
},
{
"dateTime": "2017-05-07",
"value": "6"
},
{
"dateTime": "2017-05-08",
"value": "5"
},
{
"dateTime": "2017-05-09",
"value": "0"
},
{
"dateTime": "2017-05-10",
"value": "9"
},
{
"dateTime": "2017-05-11",
"value": "8"
},
{
"dateTime": "2017-05-12",
"value": "7"
},
{
"dateTime": "2017-05-13",
"value": "0"
},
{
"dateTime": "2017-05-14",
"value": "0"
},
{
"dateTime": "2017-05-15",
"value": "0"
},
{
"dateTime": "2017-05-16",
"value": "0"
},
{
"dateTime": "2017-05-17",
"value": "4"
},
{
"dateTime": "2017-05-18",
"value": "9"
},
{
"dateTime": "2017-05-19",
"value": "7"
},
{
"dateTime": "2017-05-20",
"value": "0"
},
{
"dateTime": "2017-05-21",
"value": "0"
},
{
"dateTime": "2017-05-22",
"value": "2"
},
{
"dateTime": "2017-05-23",
"value": "0"
},
{
"dateTime": "2017-05-24",
"value": "6"
},
{
"dateTime": "2017-05-25",
"value": "0"
},
{
"dateTime": "2017-05-26",
"value": "4"
},
{
"dateTime": "2017-05-27",
"value": "0"
},
{
"dateTime": "2017-05-28",
"value": "8"
},
{
"dateTime": "2017-05-29",
"value": "0"
},
{
"dateTime": "2017-05-30",
"value": "0"
},
{
"dateTime": "2017-05-31",
"value": "0"
}
]
}]

In [17]:
d = json_normalize(fairlyAct, 'activities-minutesFairlyActive')
d

dateTime value
0   2017-05-01    13
1   2017-05-02     5
2   2017-05-03     8
3   2017-05-04    19
4   2017-05-05    21
5   2017-05-06     2
6   2017-05-07     6
7   2017-05-08     5
8   2017-05-09     0
9   2017-05-10     9
10  2017-05-11     8
11  2017-05-12     7
12  2017-05-13     0
13  2017-05-14     0
14  2017-05-15     0
15  2017-05-16     0
16  2017-05-17     4
17  2017-05-18     9
18  2017-05-19     7
19  2017-05-20     0
20  2017-05-21     0
21  2017-05-22     2
22  2017-05-23     0
23  2017-05-24     6
24  2017-05-25     0
25  2017-05-26     4
26  2017-05-27     0
27  2017-05-28     8
28  2017-05-29     0
29  2017-05-30     0
30  2017-05-31     0

In [18]:
#Get floors Time Series

floors = [{
"activities-floors": [
{
"dateTime": "2017-05-01",
"value": "22"
},
{
"dateTime": "2017-05-02",
"value": "10"
},
{
"dateTime": "2017-05-03",
"value": "9"
},
{
"dateTime": "2017-05-04",
"value": "13"
},
{
"dateTime": "2017-05-05",
"value": "6"
},
{
"dateTime": "2017-05-06",
"value": "17"
},
{
"dateTime": "2017-05-07",
"value": "16"
},
{
"dateTime": "2017-05-08",
"value": "9"
},
{
"dateTime": "2017-05-09",
"value": "11"
},
{
"dateTime": "2017-05-10",
"value": "9"
},
{
"dateTime": "2017-05-11",
"value": "5"
},
{
"dateTime": "2017-05-12",
"value": "7"
},
{
"dateTime": "2017-05-13",
"value": "7"
},
{
"dateTime": "2017-05-14",
"value": "5"
},
{
"dateTime": "2017-05-15",
"value": "1"
},
{
"dateTime": "2017-05-16",
"value": "2"
},
{
"dateTime": "2017-05-17",
"value": "1"
},
{
"dateTime": "2017-05-18",
"value": "11"
},
{
"dateTime": "2017-05-19",
"value": "8"
},
{
"dateTime": "2017-05-20",
"value": "21"
},
{
"dateTime": "2017-05-21",
"value": "8"
},
{
"dateTime": "2017-05-22",
"value": "18"
},
{
"dateTime": "2017-05-23",
"value": "8"
},
{
"dateTime": "2017-05-24",
"value": "12"
},
{
"dateTime": "2017-05-25",
"value": "8"
},
{
"dateTime": "2017-05-26",
"value": "6"
},
{
"dateTime": "2017-05-27",
"value": "12"
},
{
"dateTime": "2017-05-28",
"value": "14"
},
{
"dateTime": "2017-05-29",
"value": "25"
},
{
"dateTime": "2017-05-30",
"value": "9"
},
{
"dateTime": "2017-05-31",
"value": "7"
}
]
}]

In [19]:
e = json_normalize(floors, 'activities-floors')
e

dateTime value
0   2017-05-01    22
1   2017-05-02    10
2   2017-05-03     9
3   2017-05-04    13
4   2017-05-05     6
5   2017-05-06    17
6   2017-05-07    16
7   2017-05-08     9
8   2017-05-09    11
9   2017-05-10     9
10  2017-05-11     5
11  2017-05-12     7
12  2017-05-13     7
13  2017-05-14     5
14  2017-05-15     1
15  2017-05-16     2
16  2017-05-17     1
17  2017-05-18    11
18  2017-05-19     8
19  2017-05-20    21
20  2017-05-21     8
21  2017-05-22    18
22  2017-05-23     8
23  2017-05-24    12
24  2017-05-25     8
25  2017-05-26     6
26  2017-05-27    12
27  2017-05-28    14
28  2017-05-29    25
29  2017-05-30     9
30  2017-05-31     7

In [20]:
#Get steps Time Series

steps = [{
"activities-steps": [
{
"dateTime": "2017-05-01",
"value": "7302"
},
{
"dateTime": "2017-05-02",
"value": "17029"
},
{
"dateTime": "2017-05-03",
"value": "14127"
},
{
"dateTime": "2017-05-04",
"value": "16047"
},
{
"dateTime": "2017-05-05",
"value": "12701"
},
{
"dateTime": "2017-05-06",
"value": "18224"
},
{
"dateTime": "2017-05-07",
"value": "8640"
},
{
"dateTime": "2017-05-08",
"value": "10984"
},
{
"dateTime": "2017-05-09",
"value": "10865"
},
{
"dateTime": "2017-05-10",
"value": "12975"
},
{
"dateTime": "2017-05-11",
"value": "15855"
},
{
"dateTime": "2017-05-12",
"value": "12083"
},
{
"dateTime": "2017-05-13",
"value": "5655"
},
{
"dateTime": "2017-05-14",
"value": "3909"
},
{
"dateTime": "2017-05-15",
"value": "588"
},
{
"dateTime": "2017-05-16",
"value": "1461"
},
{
"dateTime": "2017-05-17",
"value": "12318"
},
{
"dateTime": "2017-05-18",
"value": "14154"
},
{
"dateTime": "2017-05-19",
"value": "13037"
},
{
"dateTime": "2017-05-20",
"value": "3669"
},
{
"dateTime": "2017-05-21",
"value": "4643"
},
{
"dateTime": "2017-05-22",
"value": "12861"
},
{
"dateTime": "2017-05-23",
"value": "11037"
},
{
"dateTime": "2017-05-24",
"value": "15763"
},
{
"dateTime": "2017-05-25",
"value": "11624"
},
{
"dateTime": "2017-05-26",
"value": "12987"
},
{
"dateTime": "2017-05-27",
"value": "6801"
},
{
"dateTime": "2017-05-28",
"value": "9253"
},
{
"dateTime": "2017-05-29",
"value": "5633"
},
{
"dateTime": "2017-05-30",
"value": "12264"
},
{
"dateTime": "2017-05-31",
"value": "11430"
}
]
}]

In [21]:
f = json_normalize(steps, 'activities-steps')
f

dateTime  value
0   2017-05-01   7302
1   2017-05-02  17029
2   2017-05-03  14127
3   2017-05-04  16047
4   2017-05-05  12701
5   2017-05-06  18224
6   2017-05-07   8640
7   2017-05-08  10984
8   2017-05-09  10865
9   2017-05-10  12975
10  2017-05-11  15855
11  2017-05-12  12083
12  2017-05-13   5655
13  2017-05-14   3909
14  2017-05-15    588
15  2017-05-16   1461
16  2017-05-17  12318
17  2017-05-18  14154
18  2017-05-19  13037
19  2017-05-20   3669
20  2017-05-21   4643
21  2017-05-22  12861
22  2017-05-23  11037
23  2017-05-24  15763
24  2017-05-25  11624
25  2017-05-26  12987
26  2017-05-27   6801
27  2017-05-28   9253
28  2017-05-29   5633
29  2017-05-30  12264
30  2017-05-31  11430

In [22]:
#Get veryActiveMinutes Time Series

veryAct = [{
"activities-minutesVeryActive": [
{
"dateTime": "2017-05-01",
"value": "36"
},
{
"dateTime": "2017-05-02",
"value": "28"
},
{
"dateTime": "2017-05-03",
"value": "33"
},
{
"dateTime": "2017-05-04",
"value": "39"
},
{
"dateTime": "2017-05-05",
"value": "0"
},
{
"dateTime": "2017-05-06",
"value": "65"
},
{
"dateTime": "2017-05-07",
"value": "34"
},
{
"dateTime": "2017-05-08",
"value": "46"
},
{
"dateTime": "2017-05-09",
"value": "0"
},
{
"dateTime": "2017-05-10",
"value": "40"
},
{
"dateTime": "2017-05-11",
"value": "23"
},
{
"dateTime": "2017-05-12",
"value": "29"
},
{
"dateTime": "2017-05-13",
"value": "0"
},
{
"dateTime": "2017-05-14",
"value": "0"
},
{
"dateTime": "2017-05-15",
"value": "35"
},
{
"dateTime": "2017-05-16",
"value": "0"
},
{
"dateTime": "2017-05-17",
"value": "35"
},
{
"dateTime": "2017-05-18",
"value": "39"
},
{
"dateTime": "2017-05-19",
"value": "43"
},
{
"dateTime": "2017-05-20",
"value": "21"
},
{
"dateTime": "2017-05-21",
"value": "21"
},
{
"dateTime": "2017-05-22",
"value": "46"
},
{
"dateTime": "2017-05-23",
"value": "0"
},
{
"dateTime": "2017-05-24",
"value": "37"
},
{
"dateTime": "2017-05-25",
"value": "0"
},
{
"dateTime": "2017-05-26",
"value": "35"
},
{
"dateTime": "2017-05-27",
"value": "21"
},
{
"dateTime": "2017-05-28",
"value": "28"
},
{
"dateTime": "2017-05-29",
"value": "21"
},
{
"dateTime": "2017-05-30",
"value": "0"
},
{
"dateTime": "2017-05-31",
"value": "0"
}
]
}]

In [23]:
g = json_normalize(veryAct, 'activities-minutesVeryActive')
g

dateTime value
0   2017-05-01    36
1   2017-05-02    28
2   2017-05-03    33
3   2017-05-04    39
4   2017-05-05     0
5   2017-05-06    65
6   2017-05-07    34
7   2017-05-08    46
8   2017-05-09     0
9   2017-05-10    40
10  2017-05-11    23
11  2017-05-12    29
12  2017-05-13     0
13  2017-05-14     0
14  2017-05-15    35
15  2017-05-16     0
16  2017-05-17    35
17  2017-05-18    39
18  2017-05-19    43
19  2017-05-20    21
20  2017-05-21    21
21  2017-05-22    46
22  2017-05-23     0
23  2017-05-24    37
24  2017-05-25     0
25  2017-05-26    35
26  2017-05-27    21
27  2017-05-28    28
28  2017-05-29    21
29  2017-05-30     0
30  2017-05-31     0

In [24]:
#Get ActivityCalories Time Series

ActCal = [{
"activities-activityCalories": [
{
"dateTime": "2017-05-01",
"value": "748"
},
{
"dateTime": "2017-05-02",
"value": "1281"
},
{
"dateTime": "2017-05-03",
"value": "1230"
},
{
"dateTime": "2017-05-04",
"value": "1402"
},
{
"dateTime": "2017-05-05",
"value": "1020"
},
{
"dateTime": "2017-05-06",
"value": "1181"
},
{
"dateTime": "2017-05-07",
"value": "836"
},
{
"dateTime": "2017-05-08",
"value": "1028"
},
{
"dateTime": "2017-05-09",
"value": "787"
},
{
"dateTime": "2017-05-10",
"value": "1117"
},
{
"dateTime": "2017-05-11",
"value": "1202"
},
{
"dateTime": "2017-05-12",
"value": "1066"
},
{
"dateTime": "2017-05-13",
"value": "576"
},
{
"dateTime": "2017-05-14",
"value": "364"
},
{
"dateTime": "2017-05-15",
"value": "413"
},
{
"dateTime": "2017-05-16",
"value": "147"
},
{
"dateTime": "2017-05-17",
"value": "1080"
},
{
"dateTime": "2017-05-18",
"value": "1159"
},
{
"dateTime": "2017-05-19",
"value": "1165"
},
{
"dateTime": "2017-05-20",
"value": "479"
},
{
"dateTime": "2017-05-21",
"value": "584"
},
{
"dateTime": "2017-05-22",
"value": "1105"
},
{
"dateTime": "2017-05-23",
"value": "879"
},
{
"dateTime": "2017-05-24",
"value": "1298"
},
{
"dateTime": "2017-05-25",
"value": "921"
},
{
"dateTime": "2017-05-26",
"value": "1117"
},
{
"dateTime": "2017-05-27",
"value": "722"
},
{
"dateTime": "2017-05-28",
"value": "827"
},
{
"dateTime": "2017-05-29",
"value": "689"
},
{
"dateTime": "2017-05-30",
"value": "1022"
},
{
"dateTime": "2017-05-31",
"value": "886"
}
]
}]

In [25]:
h = json_normalize(ActCal, 'activities-activityCalories')
h

dateTime value
0   2017-05-01   748
1   2017-05-02  1281
2   2017-05-03  1230
3   2017-05-04  1402
4   2017-05-05  1020
5   2017-05-06  1181
6   2017-05-07   836
7   2017-05-08  1028
8   2017-05-09   787
9   2017-05-10  1117
10  2017-05-11  1202
11  2017-05-12  1066
12  2017-05-13   576
13  2017-05-14   364
14  2017-05-15   413
15  2017-05-16   147
16  2017-05-17  1080
17  2017-05-18  1159
18  2017-05-19  1165
19  2017-05-20   479
20  2017-05-21   584
21  2017-05-22  1105
22  2017-05-23   879
23  2017-05-24  1298
24  2017-05-25   921
25  2017-05-26  1117
26  2017-05-27   722
27  2017-05-28   827
28  2017-05-29   689
29  2017-05-30  1022
30  2017-05-31   886

In [26]:
import pandas as pd

first_merge = pd.merge(c, h, on='dateTime', how='outer', suffixes=('_elevation', '_activityCalories'))
first_merge

dateTime value_elevation value_activityCalories
0   2017-05-01              67                    748
1   2017-05-02              30                   1281
2   2017-05-03              27                   1230
3   2017-05-04              39                   1402
4   2017-05-05              18                   1020
5   2017-05-06              51                   1181
6   2017-05-07              48                    836
7   2017-05-08              27                   1028
8   2017-05-09              33                    787
9   2017-05-10              27                   1117
10  2017-05-11              15                   1202
11  2017-05-12              21                   1066
12  2017-05-13              21                    576
13  2017-05-14              15                    364
14  2017-05-15               3                    413
15  2017-05-16               6                    147
16  2017-05-17               3                   1080
17  2017-05-18              33                   1159
18  2017-05-19              24                   1165
19  2017-05-20              64                    479
20  2017-05-21              24                    584
21  2017-05-22              54                   1105
22  2017-05-23              24                    879
23  2017-05-24              36                   1298
24  2017-05-25              24                    921
25  2017-05-26              18                   1117
26  2017-05-27              36                    722
27  2017-05-28              42                    827
28  2017-05-29              76                    689
29  2017-05-30              27                   1022
30  2017-05-31              21                    886

In [27]:
second_merge = pd.merge(pd.merge(first_merge,d,on='dateTime'),e,on='dateTime', suffixes=('_fairlyActiveMinutes', '_floors'))
second_merge


dateTime value_elevation value_activityCalories  \
0   2017-05-01              67                    748   
1   2017-05-02              30                   1281   
2   2017-05-03              27                   1230   
3   2017-05-04              39                   1402   
4   2017-05-05              18                   1020   
5   2017-05-06              51                   1181   
6   2017-05-07              48                    836   
7   2017-05-08              27                   1028   
8   2017-05-09              33                    787   
9   2017-05-10              27                   1117   
10  2017-05-11              15                   1202   
11  2017-05-12              21                   1066   
12  2017-05-13              21                    576   
13  2017-05-14              15                    364   
14  2017-05-15               3                    413   
15  2017-05-16               6                    147   
16  2017-05-17               3                   1080   
17  2017-05-18              33                   1159   
18  2017-05-19              24                   1165   
19  2017-05-20              64                    479   
20  2017-05-21              24                    584   
21  2017-05-22              54                   1105   
22  2017-05-23              24                    879   
23  2017-05-24              36                   1298   
24  2017-05-25              24                    921   
25  2017-05-26              18                   1117   
26  2017-05-27              36                    722   
27  2017-05-28              42                    827   
28  2017-05-29              76                    689   
29  2017-05-30              27                   1022   
30  2017-05-31              21                    886   

   value_fairlyActiveMinutes value_floors  
0                         13           22  
1                          5           10  
2                          8            9  
3                         19           13  
4                         21            6  
5                          2           17  
6                          6           16  
7                          5            9  
8                          0           11  
9                          9            9  
10                         8            5  
11                         7            7  
12                         0            7  
13                         0            5  
14                         0            1  
15                         0            2  
16                         4            1  
17                         9           11  
18                         7            8  
19                         0           21  
20                         0            8  
21                         2           18  
22                         0            8  
23                         6           12  
24                         0            8  
25                         4            6  
26                         0           12  
27                         8           14  
28                         0           25  
29                         0            9  
30                         0            7

In [28]:
#Final Merge
final_merge = pd.merge(pd.merge(second_merge,f,on='dateTime'),g,on='dateTime', suffixes=('_steps', '_veryActiveMinutes'))
final_merge

dateTime value_elevation value_activityCalories  \
0   2017-05-01              67                    748   
1   2017-05-02              30                   1281   
2   2017-05-03              27                   1230   
3   2017-05-04              39                   1402   
4   2017-05-05              18                   1020   
5   2017-05-06              51                   1181   
6   2017-05-07              48                    836   
7   2017-05-08              27                   1028   
8   2017-05-09              33                    787   
9   2017-05-10              27                   1117   
10  2017-05-11              15                   1202   
11  2017-05-12              21                   1066   
12  2017-05-13              21                    576   
13  2017-05-14              15                    364   
14  2017-05-15               3                    413   
15  2017-05-16               6                    147   
16  2017-05-17               3                   1080   
17  2017-05-18              33                   1159   
18  2017-05-19              24                   1165   
19  2017-05-20              64                    479   
20  2017-05-21              24                    584   
21  2017-05-22              54                   1105   
22  2017-05-23              24                    879   
23  2017-05-24              36                   1298   
24  2017-05-25              24                    921   
25  2017-05-26              18                   1117   
26  2017-05-27              36                    722   
27  2017-05-28              42                    827   
28  2017-05-29              76                    689   
29  2017-05-30              27                   1022   
30  2017-05-31              21                    886   

   value_fairlyActiveMinutes value_floors value_steps value_veryActiveMinutes  
0                         13           22        7302                      36  
1                          5           10       17029                      28  
2                          8            9       14127                      33  
3                         19           13       16047                      39  
4                         21            6       12701                       0  
5                          2           17       18224                      65  
6                          6           16        8640                      34  
7                          5            9       10984                      46  
8                          0           11       10865                       0  
9                          9            9       12975                      40  
10                         8            5       15855                      23  
11                         7            7       12083                      29  
12                         0            7        5655                       0  
13                         0            5        3909                       0  
14                         0            1         588                      35  
15                         0            2        1461                       0  
16                         4            1       12318                      35  
17                         9           11       14154                      39  
18                         7            8       13037                      43  
19                         0           21        3669                      21  
20                         0            8        4643                      21  
21                         2           18       12861                      46  
22                         0            8       11037                       0  
23                         6           12       15763                      37  
24                         0            8       11624                       0  
25                         4            6       12987                      35  
26                   

In [29]:
final_merge.head()

dateTime value_elevation value_activityCalories  \
0  2017-05-01              67                    748   
1  2017-05-02              30                   1281   
2  2017-05-03              27                   1230   
3  2017-05-04              39                   1402   
4  2017-05-05              18                   1020   

  value_fairlyActiveMinutes value_floors value_steps value_veryActiveMinutes  
0                        13           22        7302                      36  
1                         5           10       17029                      28  
2                         8            9       14127                      33  
3                        19           13       16047                      39  
4                        21            6       12701                       0

In [30]:
final_merge.describe()

dateTime value_elevation value_activityCalories  \
count           31              31                     31   
unique          31              18                     30   
top     2017-05-10              24                   1117   
freq             1               4                      2   

       value_fairlyActiveMinutes value_floors value_steps  \
count                         31           31          31   
unique                        11           18          31   
top                            0            9       10865   
freq                          13            4           1   

       value_veryActiveMinutes  
count                       31  
unique                      15  
top                          0  
freq                         9

In [31]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31 entries, 0 to 30
Data columns (total 7 columns):
dateTime                     31 non-null object
value_elevation              31 non-null object
value_activityCalories       31 non-null object
value_fairlyActiveMinutes    31 non-null object
value_floors                 31 non-null object
value_steps                  31 non-null object
value_veryActiveMinutes      31 non-null object
dtypes: object(7)
memory usage: 1.9+ KB


In [32]:
#Need to make a copy of main DF before modifying it for analysis.

DF_copy = final_merge.copy()
DF_copy

dateTime value_elevation value_activityCalories  \
0   2017-05-01              67                    748   
1   2017-05-02              30                   1281   
2   2017-05-03              27                   1230   
3   2017-05-04              39                   1402   
4   2017-05-05              18                   1020   
5   2017-05-06              51                   1181   
6   2017-05-07              48                    836   
7   2017-05-08              27                   1028   
8   2017-05-09              33                    787   
9   2017-05-10              27                   1117   
10  2017-05-11              15                   1202   
11  2017-05-12              21                   1066   
12  2017-05-13              21                    576   
13  2017-05-14              15                    364   
14  2017-05-15               3                    413   
15  2017-05-16               6                    147   
16  2017-05-17               3                   1080   
17  2017-05-18              33                   1159   
18  2017-05-19              24                   1165   
19  2017-05-20              64                    479   
20  2017-05-21              24                    584   
21  2017-05-22              54                   1105   
22  2017-05-23              24                    879   
23  2017-05-24              36                   1298   
24  2017-05-25              24                    921   
25  2017-05-26              18                   1117   
26  2017-05-27              36                    722   
27  2017-05-28              42                    827   
28  2017-05-29              76                    689   
29  2017-05-30              27                   1022   
30  2017-05-31              21                    886   

   value_fairlyActiveMinutes value_floors value_steps value_veryActiveMinutes  
0                         13           22        7302                      36  
1                          5           10       17029                      28  
2                          8            9       14127                      33  
3                         19           13       16047                      39  
4                         21            6       12701                       0  
5                          2           17       18224                      65  
6                          6           16        8640                      34  
7                          5            9       10984                      46  
8                          0           11       10865                       0  
9                          9            9       12975                      40  
10                         8            5       15855                      23  
11                         7            7       12083                      29  
12                         0            7        5655                       0  
13                         0            5        3909                       0  
14                         0            1         588                      35  
15                         0            2        1461                       0  
16                         4            1       12318                      35  
17                         9           11       14154                      39  
18                         7            8       13037                      43  
19                         0           21        3669                      21  
20                         0            8        4643                      21  
21                         2           18       12861                      46  
22                         0            8       11037                       0  
23                         6           12       15763                      37  
24                         0            8       11624                       0  
25                         4            6       12987                      35  
26                   

In [33]:
DF_copy.head()

dateTime value_elevation value_activityCalories  \
0  2017-05-01              67                    748   
1  2017-05-02              30                   1281   
2  2017-05-03              27                   1230   
3  2017-05-04              39                   1402   
4  2017-05-05              18                   1020   

  value_fairlyActiveMinutes value_floors value_steps value_veryActiveMinutes  
0                        13           22        7302                      36  
1                         5           10       17029                      28  
2                         8            9       14127                      33  
3                        19           13       16047                      39  
4                        21            6       12701                       0

In [34]:
DF_copy2 = DF_copy.copy()

In [35]:
DF_copy2.head() #with dateTime; for further data manipulation

dateTime value_elevation value_activityCalories  \
0  2017-05-01              67                    748   
1  2017-05-02              30                   1281   
2  2017-05-03              27                   1230   
3  2017-05-04              39                   1402   
4  2017-05-05              18                   1020   

  value_fairlyActiveMinutes value_floors value_steps value_veryActiveMinutes  
0                        13           22        7302                      36  
1                         5           10       17029                      28  
2                         8            9       14127                      33  
3                        19           13       16047                      39  
4                        21            6       12701                       0

In [36]:
del DF_copy['dateTime']

In [37]:
DF_copy #No dateTime; now ready for Correlation Matrix/Scatter Matrix Plot

value_elevation value_activityCalories value_fairlyActiveMinutes  \
0               67                    748                        13   
1               30                   1281                         5   
2               27                   1230                         8   
3               39                   1402                        19   
4               18                   1020                        21   
5               51                   1181                         2   
6               48                    836                         6   
7               27                   1028                         5   
8               33                    787                         0   
9               27                   1117                         9   
10              15                   1202                         8   
11              21                   1066                         7   
12              21                    576                         0   
13              15                    364                         0   
14               3                    413                         0   
15               6                    147                         0   
16               3                   1080                         4   
17              33                   1159                         9   
18              24                   1165                         7   
19              64                    479                         0   
20              24                    584                         0   
21              54                   1105                         2   
22              24                    879                         0   
23              36                   1298                         6   
24              24                    921                         0   
25              18                   1117                         4   
26              36                    722                         0   
27              42                    827                         8   
28              76                    689                         0   
29              27                   1022                         0   
30              21                    886                         0   

   value_floors value_steps value_veryActiveMinutes  
0            22        7302                      36  
1            10       17029                      28  
2             9       14127                      33  
3            13       16047                      39  
4             6       12701                       0  
5            17       18224                      65  
6            16        8640                      34  
7             9       10984                      46  
8            11       10865                       0  
9             9       12975                      40  
10            5       15855                      23  
11            7       12083                      29  
12            7        5655                       0  
13            5        3909                       0  
14            1         588                      35  
15            2        1461                       0  
16            1       12318                      35  
17           11       14154                      39  
18            8       13037                      43  
19           21        3669                      21  
20            8        4643                      21  
21           18       12861                      46  
22            8       11037                       0  
23           12       15763                      37  
24            8       11624                       0  
25            6       12987                      35  
26           12        6801                      21  
27           14        9253                      28  
28           25        5633                      21  
29            9       12264                       0  
30            7       11430                       0

In [38]:
##Linear Regression

In [39]:
# (a) Train the model with all May data points, except for
# the last two in the timeline (a.k.a. held-out points, a.k.a. test set).

#DF without dateTime and without value_activityCalories needed for training set.

a = DF_copy.drop('value_activityCalories', axis = 1)
b = DF_copy['value_activityCalories']

trainx = a[:29]
trainy = b[:29]

testx = a[29:]
testy = b[29:]

testy

29    1022
30     886
Name: value_activityCalories, dtype: object

In [40]:
#Training Linear Regression (L.R.) Model

from sklearn.linear_model import LinearRegression
from sklearn import linear_model

lm = linear_model.LinearRegression().fit(trainx, trainy)
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [41]:
lm.predict(trainx)

array([  820.5230089 ,  1287.23877994,  1157.69189234,  1340.2152441 ,
        1070.20730917,  1424.02279479,   821.98646721,   998.3375003 ,
         827.84046877,  1118.24002761,  1236.64836236,  1029.56635689,
         542.68074962,   448.65151711,   368.32496298,   317.27257781,
        1055.48665606,  1177.42054073,  1120.38588873,   496.89049595,
         541.9954829 ,  1065.34270315,   844.54376801,  1242.292891  ,
         877.72097183,  1081.66204511,   654.65635013,   856.56769135,
         598.58649514])

In [42]:
#Graph L.R. model. This is based on one set of predictions for a span of 29 days.

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title="Day 1- 29 Predictions")

# add a line renderer
p.line(list(range(30)), lm.predict(trainx), line_width=2)


p.xaxis.axis_label = "Day #"
p.yaxis.axis_label = "Prediction (value_activityCalories)"

show(p)

Loading BokehJS ...

/Users/mindyng/anaconda2/lib/python2.7/site-packages/bokeh/models/sources.py:89: BokehUserWarning: ColumnDataSource's columns must be of the same length
  lambda: warnings.warn("ColumnDataSource's columns must be of the same length", BokehUserWarning))


In [43]:
#Now predict activity_Calories
lm.predict(testx)

array([ 911.56644244,  869.08339373])

In [44]:
#Comparing these values to the actual (original) values:
testy

29    1022
30     886
Name: value_activityCalories, dtype: object

In [45]:
# first prediction is not as close as second prediction to actual values.

In [46]:
# (b) Compute RMSE

from sklearn.metrics import mean_squared_error
import numpy as np

calories_predictions = lm.predict(trainx)
lin_mse = mean_squared_error(trainy, calories_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse #RMSE for training set

71.449922709584357

In [47]:
#Compute actual residuals on training set

# residuals = actual label values - predicted label values

calories_predictions #predicted label values

trainy = np.array(trainy, dtype=np.int32) #actual label values

trainresid1 = (trainy) - (calories_predictions)
trainresid1

array([ -72.5230089 ,   -6.23877994,   72.30810766,   61.7847559 ,
        -50.20730917, -243.02279479,   14.01353279,   29.6624997 ,
        -40.84046877,   -1.24002761,  -34.64836236,   36.43364311,
         33.31925038,  -84.65151711,   44.67503702, -170.27257781,
         24.51334394,  -18.42054073,   44.61411127,  -17.89049595,
         42.0045171 ,   39.65729685,   34.45623199,   55.707109  ,
         43.27902817,   35.33795489,   67.34364987,  -29.56769135,
         90.41350486])

In [48]:
# (c) Compute RMSE and actual residuals for test set

calories_predictions2 = lm.predict(testx)
lin_mse = mean_squared_error(testy, calories_predictions2)
lin_rmse = np.sqrt(lin_mse)
lin_rmse #RMSE for test set

78.999184179352127

In [49]:
#actual residuals for test set

# residuals = actual label values - predicted label values

calories_predictions2 #predicted label values

testy = np.array(testy, dtype=np.int32) #actual label values

testresid1 = (testy) - (calories_predictions2)
testresid1

array([ 110.43355756,   16.91660627])

In [50]:
trainy

array([ 748, 1281, 1230, 1402, 1020, 1181,  836, 1028,  787, 1117, 1202,
       1066,  576,  364,  413,  147, 1080, 1159, 1165,  479,  584, 1105,
        879, 1298,  921, 1117,  722,  827,  689], dtype=int32)

In [51]:
calories_predictions

array([  820.5230089 ,  1287.23877994,  1157.69189234,  1340.2152441 ,
        1070.20730917,  1424.02279479,   821.98646721,   998.3375003 ,
         827.84046877,  1118.24002761,  1236.64836236,  1029.56635689,
         542.68074962,   448.65151711,   368.32496298,   317.27257781,
        1055.48665606,  1177.42054073,  1120.38588873,   496.89049595,
         541.9954829 ,  1065.34270315,   844.54376801,  1242.292891  ,
         877.72097183,  1081.66204511,   654.65635013,   856.56769135,
         598.58649514])

In [52]:
#TRAINING DATA

In [53]:
# (d) Show predicted versus actual scatter plot,
# and plot y = x as a reference line

#Each x-y pt is connected to following pt with a segment.
#The line starts at 748, 820.5230089, not near the origin.

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title="L.R.: Training Data: Prediction vs. Actual")

# add a line renderer
p.line(np.array(trainy), calories_predictions, line_width=2)

p.line([0,400,600,800,1000,1200,1400], [0,400,600,800,1000,1200,1400], color="firebrick", line_width=2)

p.xaxis.axis_label = "Actual (value_activityCalories)"
p.yaxis.axis_label = "Prediction (value_activityCalories)"           
           
show(p)


Loading BokehJS ...

In [54]:
## NON ABSOLUTE VALUES OF RESIDUALS
#(e) Show residuals scatter plot
# and plot the line y = 0 as a reference

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title = "L.R.: Training Data Residuals")

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 
         [-72.5230089 ,   -6.23877994,   72.30810766,   61.7847559 ,
        -50.20730917, -243.02279479,   14.01353279,   29.6624997 ,
        -40.84046877,   -1.24002761,  -34.64836236,   36.43364311,
         33.31925038,  -84.65151711,   44.67503702, -170.27257781,
         24.51334394,  -18.42054073,   44.61411127,  -17.89049595,
         42.0045171 ,   39.65729685,   34.45623199,   55.707109  ,
         43.27902817,   35.33795489,   67.34364987,  -29.56769135,
         90.41350486], 
         size=20, color="navy", alpha=0.5)

p.line([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], y=0, line_width=2)

p.xaxis.axis_label = "Day"
p.yaxis.axis_label = "Residuals" 

# show the results
show(p)


Loading BokehJS ...

In [55]:
## ABSOLUTE VALUES OF RESIDUALS
#(e) Show residuals scatter plot
# and plot the line y = 0 as a reference

from bokeh.plotting import figure, output_file, show

# output to static HTML file
output_file("line.html")

p = figure(plot_width=400, plot_height=400, title = "L.R.: Training Data Residuals")

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 
         [  72.5230089 ,    6.23877994,   72.30810766,   61.7847559 ,
         50.20730917,  243.02279479,   14.01353279,   29.6624997 ,
         40.84046877,    1.24002761,   34.64836236,   36.43364311,
         33.31925038,   84.65151711,   44.67503702,  170.27257781,
         24.51334394,   18.42054073,   44.61411127,   17.89049595,
         42.0045171 ,   39.65729685,   34.45623199,   55.707109  ,
         43.27902817,   35.33795489,   67.34364987,   29.56769135,
         90.41350486], 
         size=20, color="navy", alpha=0.5)

p.line([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], y=0, line_width=2)

p.xaxis.axis_label = "Day"
p.yaxis.axis_label = "Absolute value of Residuals" 

# show the results
show(p)

In [56]:
trainresid1

array([ -72.5230089 ,   -6.23877994,   72.30810766,   61.7847559 ,
        -50.20730917, -243.02279479,   14.01353279,   29.6624997 ,
        -40.84046877,   -1.24002761,  -34.64836236,   36.43364311,
         33.31925038,  -84.65151711,   44.67503702, -170.27257781,
         24.51334394,  -18.42054073,   44.61411127,  -17.89049595,
         42.0045171 ,   39.65729685,   34.45623199,   55.707109  ,
         43.27902817,   35.33795489,   67.34364987,  -29.56769135,
         90.41350486])

In [57]:
abs(trainresid1)

array([  72.5230089 ,    6.23877994,   72.30810766,   61.7847559 ,
         50.20730917,  243.02279479,   14.01353279,   29.6624997 ,
         40.84046877,    1.24002761,   34.64836236,   36.43364311,
         33.31925038,   84.65151711,   44.67503702,  170.27257781,
         24.51334394,   18.42054073,   44.61411127,   17.89049595,
         42.0045171 ,   39.65729685,   34.45623199,   55.707109  ,
         43.27902817,   35.33795489,   67.34364987,   29.56769135,
         90.41350486])

In [58]:
#TEST DATA

In [59]:
np.array(testy)

array([1022,  886], dtype=int32)

In [60]:
calories_predictions2

array([ 911.56644244,  869.08339373])

In [61]:
# (d) Show predicted versus actual scatter plot,
# and plot y = x as a reference line


from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title="L.R.: Test Data: Prediction vs. Actual")

# add a line renderer
p.line(np.array(testy), calories_predictions2, line_width=2)

p.line([0,400,600,800,1000,1200,1400], [0,400,600,800,1000,1200,1400], color="firebrick", line_width=2)

p.xaxis.axis_label = "Actual (value_activityCalories)"
p.yaxis.axis_label = "Prediction (value_activityCalories)"           
           
show(p)


Loading BokehJS ...

In [62]:
testresid1

array([ 110.43355756,   16.91660627])

In [63]:
## NON ABSOLUTE VALUES OF RESIDUALS
#(e) Show residuals scatter plot
# and plot the line y = 0 as a reference

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title = "L.R.: Test Data Residuals")

# add a circle renderer with a size, color, and alpha
p.circle([1, 2], 
         [ 110.43355756,   16.91660627], 
         size=20, color="navy", alpha=0.5)

p.line([1, 2], y=0, line_width=2)

p.xaxis.axis_label = "Day"
p.yaxis.axis_label = "Residuals" 

# show the results
show(p)


Loading BokehJS ...

In [64]:
##Decision Trees

In [65]:
# (a) Train the model with all May data points, except for
# the last two in the timeline (a.k.a. held-out points, a.k.a. test set).

from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor()
tree_reg.fit(trainx,trainy)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

In [66]:
# (b) Compute RMSE and actual residuals for training set

calories_predictions3 = tree_reg.predict(trainx)
tree_mse = mean_squared_error(trainy, calories_predictions3)
tree_rmse = np.sqrt(tree_mse)
tree_rmse #RMSE for training set
#Is prediction really this good? No error at all?

0.0

In [67]:
#actual residuals for training set

# residuals = actual training values - predicted training values

calories_predictions3 #predicted label values

trainy = np.array(trainy, dtype=np.int32) #actual label values

trainresid3 = (trainy) - (calories_predictions3)
trainresid3

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [68]:
# (c) Compute RMSE and actual residuals for test set

In [69]:
calories_predictions4 = tree_reg.predict(testx)
tree_mse = mean_squared_error(testy, calories_predictions4)
tree_rmse = np.sqrt(tree_mse)
tree_rmse #RMSE for test set

75.584389922787622

In [70]:
#actual residuals for test set

# residuals = actual training values - predicted training values

calories_predictions4 #predicted label values

testy = np.array(testy, dtype=np.int32) #actual label values

testresid4 = (testy) - (calories_predictions4)
testresid4

array([ 101.,  -35.])

In [71]:
#TRAINING DATA

In [72]:
calories_predictions3

array([  748.,  1281.,  1230.,  1402.,  1020.,  1181.,   836.,  1028.,
         787.,  1117.,  1202.,  1066.,   576.,   364.,   413.,   147.,
        1080.,  1159.,  1165.,   479.,   584.,  1105.,   879.,  1298.,
         921.,  1117.,   722.,   827.,   689.])

In [73]:
# (d) Show predicted versus actual scatter plot, and plot the line y = x as a reference

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title="D.T.: Training Data: Prediction vs. Actual")

# add a line renderer
p.line(np.array(testy), calories_predictions3, line_width=2)

p.line([0,400,600,800,1000,1200,1400], [0,400,600,800,1000,1200,1400], color="firebrick", line_width=2)

p.xaxis.axis_label = "Actual (value_activityCalories)"
p.yaxis.axis_label = "Prediction (value_activityCalories)"           
           
show(p)

Loading BokehJS ...

/Users/mindyng/anaconda2/lib/python2.7/site-packages/bokeh/models/sources.py:89: BokehUserWarning: ColumnDataSource's columns must be of the same length
  lambda: warnings.warn("ColumnDataSource's columns must be of the same length", BokehUserWarning))


In [74]:
# (e) Show residuals scatter plot, and plot the line y = 0 as a reference

In [75]:
trainresid3

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [76]:
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title = "D.T.: Training Data Residuals")

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 
         [  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.], 
         size=20, color="navy", alpha=0.5)

p.line([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], y=0, line_width=2)

p.xaxis.axis_label = "Day"
p.yaxis.axis_label = "Absolute value of Residuals" 

# show the results
show(p)

Loading BokehJS ...

In [77]:
#TEST DATA

In [78]:
calories_predictions4

array([ 921.,  921.])

In [79]:
testy

array([1022,  886], dtype=int32)

In [80]:
# (d) Show predicted versus actual scatter plot,
# and plot y = x as a reference line


from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title="D.T.: Test Data: Prediction vs. Actual")

# add a line renderer
p.line(np.array(testy), calories_predictions4, line_width=2)

p.line([0,400,600,800,1000,1200,1400], [0,400,600,800,1000,1200,1400], color="firebrick", line_width=2)

p.xaxis.axis_label = "Actual (value_activityCalories)"
p.yaxis.axis_label = "Prediction (value_activityCalories)"           
           
show(p)


Loading BokehJS ...

In [81]:
testresid4

array([ 101.,  -35.])

In [82]:
## NON ABSOLUTE VALUES OF RESIDUALS
#(e) Show residuals scatter plot
# and plot the line y = 0 as a reference

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title = "D.T.: Test Data Residuals")

# add a circle renderer with a size, color, and alpha
p.circle([1, 2], 
         [ 101.,  -35.], 
         size=20, color="navy", alpha=0.5)

p.line([1, 2], y=0, line_width=2)

p.xaxis.axis_label = "Day"
p.yaxis.axis_label = "Residuals" 

# show the results
show(p)

Loading BokehJS ...

In [83]:
##Random Forests

In [84]:
# (a) Train the model with all May data points, except for
# the last two in the timeline (a.k.a. held-out points, a.k.a. test set).

from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()
forest_reg.fit(trainx, trainy)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [85]:
# (b) Compute RMSE and actual residuals for training set

calories_predictions5 = forest_reg.predict(trainx)
forest_mse = mean_squared_error(trainy, calories_predictions5)
forest_rmse = np.sqrt(forest_mse)
forest_rmse #RMSE for training set

47.437170788462844

In [86]:
#actual residuals for training set

# residuals = actual training values - predicted training values

calories_predictions5 #predicted label values

trainy = np.array(trainy, dtype=np.int32) #actual label values

trainresid5 = (trainy) - (calories_predictions5)
trainresid5

array([   2.3,   25.2,   15.6,   86.6,  -27.9,  -84.2,   11.5,   66.5,
        -29.9,   -4.2,  -29.3,   -1.4,    0. ,  -44.2,   20. , -161.3,
          2.8,  -38.5,   33.6,  -42. ,   72.4,   -2.4,    5.2,   30.3,
         12.1,   -6.2,   -0.2,  -26.6,   53.3])

In [87]:
# (c) Compute RMSE and actual residuals for test set

calories_predictions6 = forest_reg.predict(testx)
forest_mse = mean_squared_error(testy, calories_predictions6)
forest_rmse = np.sqrt(forest_mse)
forest_rmse #RMSE for test set

44.451884099551989

In [88]:
#actual residuals for test set

# residuals = actual training values - predicted training values

calories_predictions6 #predicted label values

testy = np.array(testy, dtype=np.int32) #actual label values

testresid6 = (testy) - (calories_predictions6)
testresid6

array([ 58.7, -22.5])

In [89]:
calories_predictions5

array([  745.7,  1255.8,  1214.4,  1315.4,  1047.9,  1265.2,   824.5,
         961.5,   816.9,  1121.2,  1231.3,  1067.4,   576. ,   408.2,
         393. ,   308.3,  1077.2,  1197.5,  1131.4,   521. ,   511.6,
        1107.4,   873.8,  1267.7,   908.9,  1123.2,   722.2,   853.6,
         635.7])

In [90]:
# (d) Show predicted versus actual scatter plot, and plot
# the line y = x as a reference

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title="R.F.: Training Data: Prediction vs. Actual")

# add a line renderer
p.line(np.array(testy), calories_predictions5, line_width=2)

p.line([0,400,600,800,1000,1200,1400], [0,400,600,800,1000,1200,1400], color="firebrick", line_width=2)

p.xaxis.axis_label = "Actual (value_activityCalories)"
p.yaxis.axis_label = "Prediction (value_activityCalories)"           
           
show(p)

Loading BokehJS ...

/Users/mindyng/anaconda2/lib/python2.7/site-packages/bokeh/models/sources.py:89: BokehUserWarning: ColumnDataSource's columns must be of the same length
  lambda: warnings.warn("ColumnDataSource's columns must be of the same length", BokehUserWarning))


In [91]:
# (e) Show residuals scatter plot, and plot the line y = 0
# as a reference

trainresid5

array([   2.3,   25.2,   15.6,   86.6,  -27.9,  -84.2,   11.5,   66.5,
        -29.9,   -4.2,  -29.3,   -1.4,    0. ,  -44.2,   20. , -161.3,
          2.8,  -38.5,   33.6,  -42. ,   72.4,   -2.4,    5.2,   30.3,
         12.1,   -6.2,   -0.2,  -26.6,   53.3])

In [92]:
#NON-ABSOLUTE Values of Residuals

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title = "R.F.: Training Data Residuals")

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 
         [23.1,   55.8,   51.3,  104.2,  -28.3,  -42.1,   19.9,   30.8,
        -26.8,   -6.6,   91.6,   27.5,  -40. ,  -11.5,   14.4, -123.2,
         76.2,  -30.8,   12.7,  -63. ,   44. ,   38.6,  -12.6,   41.9,
         -1.5,  -11.3,    4.1,   10.1,   61.3], 
         size=20, color="navy", alpha=0.5)

p.line([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], y=0, line_width=2)

p.xaxis.axis_label = "Day"
p.yaxis.axis_label = "Residuals" 

# show the results
show(p)

Loading BokehJS ...

In [93]:
abs(trainresid5)

array([   2.3,   25.2,   15.6,   86.6,   27.9,   84.2,   11.5,   66.5,
         29.9,    4.2,   29.3,    1.4,    0. ,   44.2,   20. ,  161.3,
          2.8,   38.5,   33.6,   42. ,   72.4,    2.4,    5.2,   30.3,
         12.1,    6.2,    0.2,   26.6,   53.3])

In [94]:
#ABSOLUTE values of Residuals

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title = "R.F.: Training Data Residuals")

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 
         [23.1,   55.8,   51.3,  104.2,   28.3,   42.1,   19.9,   30.8,
         26.8,    6.6,   91.6,   27.5,   40. ,   11.5,   14.4,  123.2,
         76.2,   30.8,   12.7,   63. ,   44. ,   38.6,   12.6,   41.9,
          1.5,   11.3,    4.1,   10.1,   61.3], 
         size=20, color="navy", alpha=0.5)

p.line([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], y=0, line_width=2)

p.xaxis.axis_label = "Day"
p.yaxis.axis_label = "Absolute Values of Residuals" 

# show the results
show(p)

Loading BokehJS ...

In [95]:
#TEST DATA

In [96]:
calories_predictions6

array([ 963.3,  908.5])

In [100]:
# (d) Show predicted versus actual scatter plot, and plot
# the line y = x as a reference

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title="R.F.: Test Data: Prediction vs. Actual")

# add a line renderer
p.line(np.array(testy), calories_predictions6, line_width=2)

p.line([0,400,600,800,1000,1200,1400], [0,400,600,800,1000,1200,1400], color="firebrick", line_width=2)

p.xaxis.axis_label = "Actual (value_activityCalories)"
p.yaxis.axis_label = "Prediction (value_activityCalories)"           
           
show(p)

Loading BokehJS ...

In [101]:
testresid6

array([ 58.7, -22.5])

In [102]:
## NON ABSOLUTE VALUES OF RESIDUALS
#(e) Show residuals scatter plot
# and plot the line y = 0 as a reference

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(plot_width=400, plot_height=400, title = "R.F.: Test Data Residuals")

# add a circle renderer with a size, color, and alpha
p.circle([1, 2], 
         [ 58.7, -22.5], 
         size=20, color="navy", alpha=0.5)

p.line([1, 2], y=0, line_width=2)

p.xaxis.axis_label = "Day"
p.yaxis.axis_label = "Residuals" 

# show the results
show(p)

Loading BokehJS ...

In [ ]:
#...to be continued

In [98]:
# (f) Show a table that relates actual values, predicted values,
# and residuals for each pair, for each algorithm

In [99]:

# (2) If you can get the data for June, then repeat (1) with
# May data as your training set, and June data as your test set